### ISSUE TITLE
BASIC element not called on @@rapido/falling/record/282745365

### ISSUE THREAD

**Issue by djay** [plomino/rapido.core#12]
I have 

```
elements:
    deal:
      type: ACTION
    play_card:
        type: ACTION
        label: Like
    html:
        type: BASIC
```

When accessing it via @@rapido/falling/record/282745365 my actions will display but the html element won't get called at all.
